name: Replace text in all repo

on:
  workflow_dispatch:

jobs:
  replace:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Replace 7GrandDadPGN by nozory in ALL files (excluding .git)
        run: |
          find . -type f -not -path "./.git/*" -exec sed -i 's/7GrandDadPGN/nozory/g' {} +

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Replace 7GrandDadPGN by nozory in all files"
          file_pattern: "."
